---
sudo: required
language: ruby
cache: bundler
rvm:
    - jruby-1.7.25
script:
    - bundle exec rspec spec
jdk: openjdk7
before_install:
    - sudo add-apt-repository -y ppa:openjdk-r/ppa
    - sudo apt-get -qq update
    - sudo apt-get install -y ant openjdk-8-jdk
    - sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    - sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
    - java -version
    - javac -version
    - ruby --version
